### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by ghost** [saintly2k/AbulaChan#1]
http://chan.abulafia.space/ isn't working.

**Comment by saintly2k** [comment]
sorry, didnt notice i unplugged my server from the power supply after moving things in my room. its back online for now, however make sure you use the http version and NOT the https version or else you'll get am error since i dont have a tsl/ssl certificate yet. sorry >w<

**Comment by ghost** [comment]
> sorry, didnt notice i unplugged my server from the power supply after moving things in my room. its back online for now, however make sure you use the http version and NOT the https version or else you'll get am error since i dont have a tsl/ssl certificate yet. sorry >w<

Error 523
Origin is unreachable

**Comment by ghost** [comment]
Please plug the server back in.

**Comment by saintly2k** [comment]
Please read this
https://github.com/saintly2k/AbulaChan/blob/main/README.md#important-announcement
server will be back at 13.07.2021

**Comment by ghost** [comment]
I close my eyes, for once I don't have to try
I'm well-wishing for a life, I picture you happy, oh
In the weeds, we walked, your hand running through the moss
I was so lost in thought, but you were there living
You've taken me with you
Can I slow the days? I wish that I'll find the faith
I'm dying to save your place and you'll never suffer
We'll stay together
Oh, it's not alright, that one day we're all out of time
I'll write you another life, I'm sorry for crying
It's just that I love you
One day, can't be far enough
I had lost my sight
So you sang to me, the beauty you'd been seeing
If I can't stop time
I'll build a world where God cannot take us
There's no need to think of time
But then, you said, "Don't think of the time that's left"
You're spending it in your head, I just want you laughing
I'm sorry for crying, I just want you happy
So at last, could I?
I'll be happy just to have known you
And we wished each other well

**Comment by saintly2k** [comment]
Yesyes, the server is up again since my vacations are now over and school starts again next week but >w< have fun at abulafia.space xd

**Comment by ghost** [comment]
IT'S NOT WORKING AGAIN!

Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at abulafia.space Port 80
